### PR TITLE
fix typo in nextflow_vdsl3/index.qmd

### PR DESCRIPTION
**Pull request by KaiWaldrant**

### CODE REVIEW

**Comment by Grifs** [comment]
Fixed in Viash static documentation

**Comment by rcannood** [comment]
> Fixed in Viash static documentation

Can you link to the PR / commit where this was done? ^^

**Comment by Grifs** [comment]
https://github.com/viash-io/viash/commit/1ccddf5610c2752469a3c2c358b98bdc04da0515

**Comment by rcannood** [comment]
Aha! For future reference, please edit static qmd files in the viash repo as in viash-io/viash#581.

**Pull request closed without merging**
