### PR TITLE
Update the website for viash 0.8.2

### PR DESCRIPTION
**Pull request by Grifs**
Rerendered pages for Viash 0.8.2

Probably need to think about how to better render the [repository pages](http://viash.io/pr-preview/pr-70/reference/config/functionality/dependencies/)

### CODE REVIEW

**Comment by rcannood** [comment]
Agreed!

**Comment by tverbeiren** [comment]
@DriesSchaumont @rcannood Could you take a look at the 'VDSL3 principles' page please?

Are you able to render it?

**Comment by rcannood** [comment]
In the reference I noticed:

Screenshot from 2024-02-09 08-52-42

But I'd expect the repositories to be listed in its own `/reference/config/functionality/repositories`:

Screenshot from 2024-02-09 08-52-46

------

In addition, the `.functionality.repositories` documentation should link to the `/reference/config/functionality/repositories` page.

Screenshot from 2024-02-09 08-55-20

-------

And the `.functionality.dependencies[].repository` should also link to the repository.

Screenshot from 2024-02-09 08-55-53

---

Is this still something that can be included for the 0.8.2 docs or is it a change that needs to happen at the level of Viash, and will thus be picked up in 0.8.4 or later?

**Comment by Grifs** [comment]
> Is this still something that can be included for the 0.8.2 docs or is it a change that needs to happen at the level of Viash, and will thus be picked up in 0.8.4 or later?

I guess we could fudge it in the build script, but ideally it would added on the side of Viash.
Additionally, the repositories page could use some love too.

**Comment by rcannood** [comment]
I'm happy for the changes to be included in the upcoming release, as long as we don't forget about it :relaxed: Does this work for you?

**Comment by Grifs** [comment]
Absolutely. I'll do next ;)

**Review by rcannood — APPROVED** [review]
LGTM!

**Pull request merged**
