### PR TITLE
Add 0.9.0-RC as a preview version

### PR DESCRIPTION
**Pull request by Grifs**
Add a preview render of 0.9.0-RC in the versioned dropdown

### CODE REVIEW

**Comment by Grifs** [comment]
We have the issue again that we can't properly preview the versioned versions, but you could take a look here: https://viash.io/pr-preview/pr-89/versioned/0_9_0_RC/

**Comment by Grifs** [comment]
dropdown:
image

**Comment by rcannood** [comment]
Looks ok at first glance!

Before the full 0.9 release I propose cleaning up the reference a bit because it's quite hectic right now.

| 0.8.6 | 0.9.0-RC |
|-----|------|
| Screenshot from 2024-06-25 16-04-29 | Screenshot from 2024-06-25 16-05-37 |

* Can we reorder the items to make it more readable
* Would it be a good idea to move Functionality and Platforms to a 'Deprecated' subfolder?
* Should we remove build info (since users can't use it in their config anyways)

Is there anything else we can do?

**Comment by Grifs** [comment]
I got it to 
image
so far, but unsurprisingly, it broke quite a few links

**Comment by Grifs** [comment]
Well yes, any hard coded links to the functionality or platform pages are broken if you move those pages to `.../deprecated/...`. However, that also highlights a good portion of the pages that are outdated, (this includes reference pages too).

Most reference pages have the links updated, only exception is the `viash code block`

**Review by rcannood — APPROVED** [review]

**Pull request merged**
